spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
  mapper-locations: classpath:/mapper/*.xml