# dataSource configuration
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root

# MyBatisPlus configuration
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml

# single Druid dataSource configuration
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    druid:
#      initial-size: 5 #initial connection pool count
#      min-idle: 5 #min connection pool count
#      max-active: 20 #max connection pool count
#      max-wait: 60000 # connect time out
#      stat-view-servlet:
#        login-username: admin
#        login-password: admin
#      filter:
#        stat:
#          log-slow-sql: true  #slow select
#          slow-sql-millis: 2000

# multiple Druid dataSource configuration
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true  #slow select
          slow-sql-millis: 2000
      study:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        initial-size: 5 #initial connection pool count
        min-idle: 5 #min connection pool count
        max-active: 20 #max connection pool count
        max-wait: 60000 # connect time out
      study2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/study2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        initial-size: 5 #initial connection pool count
        min-idle: 5 #min connection pool count
        max-active: 20 #max connection pool count
        max-wait: 12000 # connect time out
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8 #max connection pool count
        max-wait: -1 #connect time out
        max-idle: 8
        min-idle: 0
