# multiple Druid dataSource configuration
spring:
  datasource:
    yjstandard:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/yjstandardex?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
    study:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
# MyBatisPlus configuration
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
#  mapper-locations: classpath*:mapper/module/**/*.xml
