# dataSource configuration
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/yjstandardex?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root

# multiple Druid dataSource configuration
spring:
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true  #slow select
          slow-sql-millis: 2000
      yjstandard:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yjstandardex?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        initial-size: 5 #initial connection pool count
        min-idle: 5 #min connection pool count
        max-active: 20 #max connection pool count
        max-wait: 60000 # connect time out
      study:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        initial-size: 5 #initial connection pool count
        min-idle: 5 #min connection pool count
        max-active: 20 #max connection pool count
        max-wait: 60000 # connect time out
# MyBatisPlus configuration
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/module/**/*.xml
